apiVersion: v1
kind: Service
metadata:
  name: consul-testing-cluster
  labels:
    name: consul-testing
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  ports:
    - name: http
      port: 8500
      protocol: TCP
      targetPort: 8500
    - name: https
      port: 8443
      protocol: TCP
      targetPort: 8443
  selector:
    app: consul-testing
